//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hobby_shopEntities4 : DbContext
    {
        public Hobby_shopEntities4()
            : base("name=Hobby_shopEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Shop_Employees> Shop_Employees { get; set; }
        public virtual DbSet<Products_Rus> Products_Rus { get; set; }
        public virtual DbSet<Shop_Employees_Rus> Shop_Employees_Rus { get; set; }
    }
}
